dependencies = [
  "scheme-basic",
  "latexmk",
  "currfile",
  "filehook",
  "biblatex",
  "babel",
  "biber",
  "acmart",
  "libertine",
  "libertinus",
  "biblatex-trad",
  "biblatex-software",
  "xurl",
  "xstring",
  "microtype",
  "booktabs",
  "totpages",
  "everyshi",
  "environ",
  "setspace",
  "hyperxmp",
  "ifmtarg",
  "luacode",
  "luatexbase",
  "xcolor",
  "manyfoot",
  "caption",
  "float",
  "comment",
]
